-- MySQL Script generated by MySQL Workbench
-- Thu Nov  9 12:19:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `id_perfil` INT NULL,
  `descrição_perfil` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_Usuario` INT NOT NULL,
  `Nome_Usuario` VARCHAR(50) NOT NULL,
  `Sobrenome_Usuario` VARCHAR(50) NOT NULL,
  `CPF_Usuario` DECIMAL(11) NOT NULL,
  `Telefone_Usuario` DECIMAL(11) NOT NULL,
  `Sexo_Usuario` VARCHAR(45) NOT NULL,
  `Login_Usuario` VARCHAR(45) NOT NULL,
  `Email_Usuario` VARCHAR(45) NOT NULL,
  `Senha_Usuario` VARCHAR(45) NOT NULL,
  `perfil` INT NOT NULL,
  INDEX `fk_Usuario_Telecall_perfis_idx` (`perfil` ASC) VISIBLE,
  PRIMARY KEY (`id_Usuario`),
  CONSTRAINT `fk_Usuario_Telecall_perfis`
    FOREIGN KEY (`perfil`)
    REFERENCES `mydb`.`Perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Telecall_perfis1`
    FOREIGN KEY (`id_Usuario`)
    REFERENCES `mydb`.`Perfil` (`descrição_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
